Models/Situation.cs
namespace Projet_Jeu_Role.Models
{
    public class Situation
    {
        public int Id { get; set; }
        public string SituationName { get; set; } = string.Empty;
        public string SituationDescription { get; set; } = string.Empty;
        //public List<Answer> Answers { get; set; } = new List<Answer>();

        public virtual List<Answer> AnswerEnter { get; set; } = new List<Answer>();
        public virtual List<Answer> AnswerExit { get; set; } = new List<Answer>();


    }
}

Controllers/AnswersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projet_Jeu_Role.Data;
using Projet_Jeu_Role.Models;

namespace Projet_Jeu_Role.Controllers
{
    public class AnswersController : Controller
    {
        private readonly ProjetMVCContext _context;

        public AnswersController(ProjetMVCContext context)
        {
            _context = context;
        }

        // GET: Answers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Answers
              .Include(s => s.SituationEnter)
              .Include(s => s.SituationExit)
              .ToListAsync());
        }

        // GET: Answers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Answers == null)
            {
                return NotFound();
            }

            var answer = await _context.Answers
                .Include(s => s.SituationEnter)
                .Include(s => s.SituationExit)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (answer == null)
            {
                return NotFound();
            }

            return View(answer);
        }

        // GET: Answers/Create
        public IActionResult Create()
        {
												ViewBag.SituationEnterId = new SelectList(_context.Situations, "Id", "SituationName");
												ViewBag.SituationExitId = new SelectList(_context.Situations, "Id", "SituationName");
												return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AnswerContent,SituationEnterId,SituationExitId")] Answer answer)
        {
												if (ModelState.IsValid)
            {
                _context.Add(answer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(answer);
        }

        // GET: Answers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Answers == null)
            {
                return NotFound();
            }

            var answer = await _context.Answers.FindAsync(id);
            if (answer == null)
            {
                return NotFound();
            }
												ViewBag.SituationEnterId = new SelectList(_context.Situations, "Id", "SituationName", answer.SituationEnterId);
												ViewBag.SituationExitId = new SelectList(_context.Situations, "Id", "SituationName", answer.SituationExitId);
												return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AnswerContent,SituationEnterId,SituationExitId")] Answer answer)
        {
            if (id != answer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(answer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnswerExists(answer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(answer);
        }

        // GET: Answers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Answers == null)
            {
                return NotFound();
            }

            var answer = await _context.Answers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (answer == null)
            {
                return NotFound();
            }

            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Answers == null)
            {
                return Problem("Entity set 'ProjetMVCContext.Answers'  is null.");
            }
            var answer = await _context.Answers.FindAsync(id);
            if (answer != null)
            {
                _context.Answers.Remove(answer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnswerExists(int id)
        {
            return _context.Answers.Any(e => e.Id == id);
        }
    }
}

Controllers/SituationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Projet_Jeu_Role.Data;
using Projet_Jeu_Role.Models;

namespace Projet_Jeu_Role.Controllers
{
    public class SituationsController : Controller
    {
        private readonly ProjetMVCContext _context;

        public SituationsController(ProjetMVCContext context)
        {
            _context = context;
        }

        // GET: Situations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Situations.ToListAsync());
        }

								public IActionResult Next(Situation _situation)
								{
            try
            {
                _situation = _context.Situations
                    .Include(s => s.AnswerEnter)
                    .Where(s => s.Id == _situation.Id).First();
            }
            catch(Exception)
            {
                return View("EndGame");
            }

												return View(_situation);
								}

								// GET: Situations/Details/5
								public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Situations == null)
            {
                return NotFound();
            }

            var situation = await _context.Situations
                .Include(s => s.AnswerEnter)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (situation == null)
            {
                return NotFound();
            }

            return View(situation);
        }

        // GET: Situations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Situations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SituationName,SituationDescription")] Situation situation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(situation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(situation);
        }


        // GET: Situations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Situations == null)
            {
                return NotFound();
            }

            var situation = await _context.Situations.FindAsync(id);
            if (situation == null)
            {
                return NotFound();
            }
            return View(situation);
        }

        // POST: Situations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SituationName,SituationDescription")] Situation situation)
        {
            if (id != situation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(situation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SituationExists(situation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(situation);
        }

        // GET: Situations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Situations == null)
            {
                return NotFound();
            }

            var situation = await _context.Situations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (situation == null)
            {
                return NotFound();
            }

            return View(situation);
        }

        // POST: Situations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Situations == null)
            {
                return Problem("Entity set 'ProjetMVCContext.Situation'  is null.");
            }
            var situation = await _context.Situations.FindAsync(id);
            if (situation != null)
            {
                _context.Situations.Remove(situation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SituationExists(int id)
        {
            return _context.Situations.Any(e => e.Id == id);
        }
    }
}

Views/Situations/Create.cshtml
@model Projet_Jeu_Role.Models.Situation

@{
    ViewData["Title"] = "Création d'une situation";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
</head>
<body>

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SituationName" class="control-label"></label>
                <input asp-for="SituationName" class="form-control" />
                <span asp-validation-for="SituationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SituationDescription" class="control-label"></label>
                <input asp-for="SituationDescription" class="form-control" />
                <span asp-validation-for="SituationDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

    <div>
        <a asp-action="Index" class="btn btn-outline-primary">Retour à la liste</a>
    </div>

</body>
</html>

Views/Situations/Delete.cshtml
@model Projet_Jeu_Role.Models.Situation

@{
    ViewData["Title"] = "Suppression de la situation";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
</head>
<body>

    <div class="alert alert-danger" role="alert">
        <h2 class="alert-heading">Êtes vous sûr de vouloir supprimer cette situation ?</h2>
        <p>La suppression est une action irréversible. Les données ne seront pas récupérables après suppression.</p>
    </div>

<div>
    <h3>Détails de la situation</h3>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SituationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SituationName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SituationDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SituationDescription)
        </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Supprimer" class="btn btn-danger" />
            <a class="btn btn-outline-primary" asp-action="Index">Retour à la liste</a>
        </form>
</div>
</body>
</html>

Views/Situations/Details.cshtml
@using Projet_Jeu_Role.Controllers
@model Projet_Jeu_Role.Models.Situation

@{
	ViewData["Title"] = "Détails de la situation";
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewData["Title"]</title>
</head>
<body>

	<div>
		<h1>@ViewData["Title"]</h1>
		<hr />
		<dl class="row">
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Id)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Id)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.SituationName)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.SituationName)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.SituationDescription)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.SituationDescription)
			</dd>
		</dl>
	</div>
	<div>
		<a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Modifier la situation</a>
	</div>
	<div>
		<br />
		<h2>Réponses liées</h2>
		<hr />
		<table>
			<thead>
				<tr>
					<th>Contenu de la réponse</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@{
					foreach (var item in Model.AnswerEnter)
					{

						<tr>
							<td>
								@Html.DisplayFor(m => item.AnswerContent)
							</td>
							<td>
								<a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Détails</a>
								<a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Modifier</a>
								<a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Supprimer</a>
							</td>
						</tr>
					}
				}
			</tbody>
		</table>

		<!-- Message d'erreur s'il n'y a pas de réponses associées -->
		@{
			if (Model.AnswerEnter.Count == 0)
			{
				<div class="alert alert-secondary" role="alert">
					<p>
						Pas de réponses associées à cette situation.
					</p>
					<a class="btn btn-primary" asp-area="" asp-controller="Answers" asp-action="Index">Aller aux réponses</a>
				</div>
			}
		}
	</div>
	<div>
		<a class="btn btn-outline-primary" asp-action="Index">Retour à la liste</a>
	</div>
</body>
</html>

Views/Situations/Edit.cshtml
@model Projet_Jeu_Role.Models.Situation

@{
	ViewData["Title"] = "Edition de la situation";
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewData["Title"]</title>
</head>
<body>

	<h1>@ViewData["Title"]</h1>
	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="Edit">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="Id" />
				<div class="form-group">
					<label asp-for="SituationName" class="control-label"></label>
					<input asp-for="SituationName" class="form-control" />
					<span asp-validation-for="SituationName" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="SituationDescription" class="control-label"></label>
					<input asp-for="SituationDescription" class="form-control" />
					<span asp-validation-for="SituationDescription" class="text-danger"></span>
				</div>

				<input type="submit" value="Sauvegarder" class="btn btn-primary" />
				<a class="btn btn-outline-primary" asp-action="Index">Retour à la liste</a>
			</form>
		</div>
	</div>

</body>
</html>

Views/Situations/EndGame.cshtml
@model Projet_Jeu_Role.Models.Situation

<dl class="row">
				<dt class="col-sm-2">
								@Html.DisplayFor(m => m.SituationName)
								<br/>
								@Html.DisplayFor(m => m.SituationDescription)
					</dt>
				<dt class="col-sm-10">
					<p>Vous avez fini le jeu !</p>				
				</dt>
</dl>

Views/Situations/Index.cshtml
@model IEnumerable<Projet_Jeu_Role.Models.Situation>

@{
    ViewData["Title"] = "Liste des situations";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
</head>
<body>

    <h1>@ViewData["Title"]</h1>
    <hr/>
<p>
    <a asp-action="Create" class="btn btn-primary">Créer une situation</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SituationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SituationDescription)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SituationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SituationDescription)
            </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Détails</a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Modifier</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Supprimer</a>
                    </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

Views/Situations/Next.cshtml
@{
    ViewData["Title"] = "Espace Player";
}

<div class="text-center">
    <h1 class="display-4">Espace Player</h1>
    <partial name="../Situations/_SituationPlayer" model="Model"/>
</div>

Views/Situations/_SituationPlayer.cshtml
@model Projet_Jeu_Role.Models.Situation
				
<br />
<dl class="row">
				<dt class="col-sm-2">
								@Html.DisplayFor(m => m.SituationName)
								<br/>
								@Html.DisplayFor(m => m.SituationDescription)
					</dt>
					<dt class="col-sm-10">
								@for (int i = 0; i < Model.AnswerEnter.Count; i++)
								{
												<a asp-controller="Situations" asp-action="Next" asp-route-id="@Model.AnswerEnter[i].Id">@Html.DisplayFor(m => m.AnswerEnter[i].AnswerContent)</a>
								}
					</dt>
</dl>